{% set version = "0.29.0" %}


package:
  name: woodwork
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/woodwork/woodwork-{{ version }}.tar.gz
  sha256: 53d236a12eb20d2a23b7f6f3d9f9b77d3869adc62344c2accc3e7cfb8b4f517c

build:
  entry_points:
    - woodwork = woodwork.__main__:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9.*
  run:
    - importlib-resources >=5.10.0
    - numpy >1.25.0
    - pandas >=1.4.3
    - python >=3.9.*
    - python-dateutil >=2.8.2
    - scikit-learn >=1.1.0
    - scipy >=1.10.0
test:
  imports:
    - woodwork
    - woodwork.tests
  requires:
    - boto3 >=1.34.32
    - moto >=5.0.0
    - pyarrow >=14.0.1
    - pytest <8.0.0, >=7.0.1
    - pytest-cov >=2.10.1
    - pytest-xdist >=2.1.0
    - smart_open >=5.0.0
  source_files:
    - woodwork/tests/*
  commands:
    - pytest woodwork/tests
    - pip check

about:
  doc_url: https://woodwork.alteryx.com
  dev_url: https://github.com/alteryx/woodwork
  home: https://www.alteryx.com/open-source
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Woodwork provides a common typing namespace for using your existing DataFrames in Featuretools, EvalML, and general ML.


extra:
  recipe-maintainers:
    - machineAYX
    - simha104
    - petejanuszewski1
    - thehomebrewnerd
    - tamargrey
    - dvreed77
    - jeff-hernandez
    - Cmancuso
    - bchen1116
    - ParthivNaresh
